#
# Makefile for target specific math
#
# Copyright 2026 Phoenix Systems
# Author: Mikolaj Matalowski
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

HW_OBJS := $(addprefix $(PREFIX_O), $(patsubst %.c,%.o,$(wildcard libm/arch/$(TARGET_SUFF)/*.c)))