#
# Makefile for libphoenix (posix compatibility)
#
# Copyright 2018 Phoenix Systems
# Author: Pawel Pisarczyk
#

ARCH_SRCS := stubs.c utils.c idtree.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
