#
# Makefile for libphoenix/arch/armv7
#
# Copyright 2017, 2020 Phoenix Systems
# Author: Pawel Pisarczyk
#

OBJS += $(addprefix $(PREFIX_O)arch/armv7m/, _start.o syscalls.o jmp.o signal.o string.o reboot.o tls.o tls_internal.o)
