#
# Makefile for libphoenix - pattern rules for compiling and linking
#
# Copyright 2012-2018 Phoenix Systems
#
ifeq (,$(TOPDIR))
$(error Only main Makefile can be used for compilation)
endif

CURR_SUFFIX := $(patsubst $(TOPDIR)/%,%,$(abspath $(CURDIR))/)
PREFIX_O := $(BUILD_DIR)/$(CURR_SUFFIX)
PREFIX_A := $(BUILD_DIR)/$(CURR_SUFFIX)
PREFIX_PROG := $(BUILD_DIR)/$(CURR_SUFFIX)

$(PREFIX_O)%.o: %.c
	@mkdir -p $(@D)
	$(SIL)(printf " CC  %-24s  " "$<")
	$(SIL)$(CC) -c $(CFLAGS) "$<" -o "$@"

	@(file="$@"; \
	datasz=0;\
	textsz=0;\
	for i in `$(OBJDUMP) -t $$file | grep -e " O " | awk '{ if ($$2 != "O") print $$5; else print $$4 }'`; do \
		datasz=`echo $$(($$datasz + 0x$$i))`;\
	done; \
	for i in `$(OBJDUMP) -t $$file | grep -e " F " | awk '{ print $$5 }'`; do \
		textsz=`echo $$(($$textsz + 0x$$i))`;\
	done;\
	printf "data=%-10s\ttext=%s\n" $$datasz $$textsz)

$(PREFIX_O)%.o: %.S
	@mkdir -p $(@D)
	$(SIL)(printf " ASM %-24s  " "$<")
	$(SIL)$(CC) -c $(CFLAGS) "$<" -o "$@"

	@(file="$@"; \
	datasz=0;\
	textsz=0;\
	for i in `$(OBJDUMP) -t $$file | grep -e " O " | cut -c 18- |awk '{print $$2}'`; do \
		datasz=`echo $$(($$datasz + 0x$$i))`;\
	done; \
	for i in `$(OBJDUMP) -t $$file | grep -e " F " | cut -c 18- |awk '{print $$2}'`; do \
		textsz=`echo $$(($$textsz + 0x$$i))`;\
	done;\
	printf "data=%-10s\ttext=%s\n" $$datasz $$textsz)

$(PREFIX_A)%.a:
	@mkdir -p $(@D)
	@(printf " AR  %-24s  \n" "$*")
	$(SIL)$(AR) $(ARFLAGS) $@ $^ 2>/dev/null


$(PREFIX_PROG)%_unstripped: $(PREFIX_O)%.o $(LIB)
	@(printf " LD  %-24s  \n" "$(@F)")
	$(SIL)$(LD) $(LDFLAGS) -o "$@" $^ $(GCCLIB)

$(PROGS_OUT): %: %_unstripped
	@(printf " STR %-24s  \n" "$(@F)")
	$(SIL)$(STRIP) -s -o "$@" "$<"

# suppress 'nothing to be done'
all:
	@echo >/dev/null;

depend: check
	$(SIL)$(MKDEP) $(MKDEPFLAGS) $(SRCS) >.depend


.PHONY: all clean
