#
# Makefile for libphoenix (sys)
#
# Copyright 2017 Phoenix Systems
# Author: Pawel Pisarczyk
#

ARCH_SRCS = rb.c stat.c time.c times.c list.c resource.c semaphore.c socket.c select.c ioctl.c mount.c threads.c events.c wait.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
