#
# Makefile for libphoenix/stdio
#
# Copyright 2017, 2019, 2020 Phoenix Systems
#

OBJS += $(addprefix $(PREFIX_O)stdio/, printf.o sprintf.o asprintf.o fprintf.o format.o scanf.o file.o perror.o bignum.o)
