#
# Makefile for libphoenix/arch/armv8
#
# Copyright 2024 Phoenix Systems
# Author: Damian Loewnau
#

OBJS += $(addprefix $(PREFIX_O)arch/armv8m/, syscalls.o jmp.o signal.o string.o reboot.o tls.o)
CRT0_OBJS += $(addprefix $(PREFIX_O)arch/armv8m/, crt0.o)
