#
# Makefile for libphoenix (stdlib)
#
# Copyright 2017 Phoenix Systems
# Author: Pawel Pisarczyk
#

ARCH_SRCS := strtod.c strtoul.c strtoull.c malloc_dl.c rand.c bsearch.c exit.c qsort.c env.c pty.c abort.c random.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
