/*
 * Phoenix-RTOS
 *
 * libphoenix
 *
 * mktemp.c - create uniquely named files and directories
 *
 * Copyright 2018, 2020, 2023 Phoenix Systems
 * Author: Kamil Amanowicz, Lukasz Kosinski, Aleksander Kaminski
 *
 * This file is part of Phoenix-RTOS.
 *
 * %LICENSE%
 */

#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/minmax.h>
#include <unistd.h>

#include <sys/msg.h>
#include <sys/stat.h>

#define CONST_STRLEN(str) (sizeof(str) - 1)

#define DEFAULT_PREFIX    "file"
#define RAND_TEMPLATE     "XXXXXX"
#define RAND_TEMPLATE_LEN CONST_STRLEN(RAND_TEMPLATE)

#define TEMPNAM_PREFIX_MAXLEN 5 /* defined by POSIX */


_Static_assert(CONST_STRLEN(P_tmpdir "/" DEFAULT_PREFIX RAND_TEMPLATE) + 1 <= L_tmpnam, "L_tmpnam is too small to hold a pathname generated by tmpnam()");


/* Portable filename character set */
static const char filenameCharset[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-";


/* Generates a unique filename */
static int __mktemp(char *templt, int suffixlen)
{
	if ((templt == NULL) || (suffixlen < 0)) {
		return SET_ERRNO(-EINVAL);
	}

	int len = strlen(templt);

	if ((len < RAND_TEMPLATE_LEN) || (suffixlen > (len - RAND_TEMPLATE_LEN))) {
		return SET_ERRNO(-EINVAL);
	}

	char *tail = templt + len - suffixlen - RAND_TEMPLATE_LEN;

	if (strncmp(tail, RAND_TEMPLATE, RAND_TEMPLATE_LEN) != 0) {
		return SET_ERRNO(-EINVAL);
	}

	int fd = open("/dev/urandom", O_RDONLY);
	if (fd < 0) {
		/* errno set by open */
		return fd;
	}

	unsigned char rnd[RAND_TEMPLATE_LEN];
	ssize_t left = sizeof(rnd);
	do {
		ssize_t err;
		do {
			err = read(fd, (unsigned char *)rnd + sizeof(rnd) - left, left);
		} while ((err < 0) && (errno == EINTR));

		if (err <= 0) {
			/* errno set by read */
			err = errno;
			close(fd);
			errno = err;
			return -1;
		}
		left -= err;
	} while (left != 0);
	close(fd);

	for (int i = 0; i < sizeof(rnd) / sizeof(rnd[0]); ++i) {
		tail[i] = filenameCharset[rnd[i] % (CONST_STRLEN(filenameCharset))];
	}

	oid_t oid;
	if (lookup(templt, &oid, NULL) == 0) {
		return SET_ERRNO(-EEXIST);
	}

	return 0;
}


int mkostemps(char *templt, int suffixlen, int flags)
{
	int fd;

	if (__mktemp(templt, suffixlen) < 0) {
		return -1;
	}

	flags &= ~(O_RDONLY | O_WRONLY);
	fd = open(templt, flags | O_CREAT | O_RDWR | O_EXCL, DEFFILEMODE);
	if (fd < 0) {
		return -1;
	}

	return fd;
}


int mkstemps(char *templt, int suffixlen)
{
	return mkostemps(templt, suffixlen, 0);
}


int mkostemp(char *templt, int flags)
{
	return mkostemps(templt, 0, flags);
}


int mkstemp(char *templt)
{
	return mkstemps(templt, 0);
}


char *mkdtemp(char *templt)
{
	if (__mktemp(templt, 0) < 0) {
		return NULL;
	}

	if (mkdir(templt, S_IRUSR | S_IWUSR | S_IXUSR) < 0) {
		return NULL;
	}

	return templt;
}


static bool checkdir(const char *dir)
{
	struct stat statbuf;
	return stat(dir, &statbuf) >= 0 && S_ISDIR(statbuf.st_mode);
}


char *tmpnam(char *str)
{
	static char template[L_tmpnam];
	int err, tries = 0;
	const bool haveTmpdir = checkdir(P_tmpdir);

	if (str == NULL) {
		str = template;
	}

	do {
		sprintf(str, "%s/" DEFAULT_PREFIX RAND_TEMPLATE, haveTmpdir ? P_tmpdir : "");
		err = __mktemp(str, 0);
	} while ((err < 0) && errno == EEXIST && ++tries < TMP_MAX);

	return (err < 0) ? NULL : str;
}


char *tempnam(const char *dir, const char *pfx)
{
	int err, sep = 0, tries = 0;
	size_t dirlen, pfxlen;
	char *name, *ptr;

	if (dir == NULL || !checkdir(dir)) {
		dir = checkdir(P_tmpdir) ? P_tmpdir : "/";
	}

	if (pfx == NULL) {
		pfx = DEFAULT_PREFIX;
		pfxlen = CONST_STRLEN(DEFAULT_PREFIX);
	}
	else {
		pfxlen = min(strlen(pfx), TEMPNAM_PREFIX_MAXLEN);
	}

	dirlen = strlen(dir);
	if (dirlen > 0 && dir[dirlen - 1] != '/') {
		sep = 1;
	}

	name = malloc(dirlen + sep + pfxlen + RAND_TEMPLATE_LEN + 1);
	if (name == NULL) {
		return NULL;
	}

	do {
		ptr = name;

		memcpy(ptr, dir, dirlen);
		ptr += dirlen;

		if (sep != 0) {
			*ptr = '/';
			ptr++;
		}

		memcpy(ptr, pfx, pfxlen);
		ptr += pfxlen;

		memcpy(ptr, RAND_TEMPLATE, RAND_TEMPLATE_LEN);
		ptr += RAND_TEMPLATE_LEN;

		*ptr = '\0';

		err = __mktemp(name, 0);
	} while (err < 0 && ++tries < TMP_MAX);

	if (err < 0) {
		free(name);
		name = NULL;
	}

	return name;
}
