#
# Makefile for libphoenix/unistd
#
# Copyright 2020 Phoenix Systems
#

OBJS += $(addprefix $(PREFIX_O)unistd/, alarm.o conf.o crypt.o dir.o ioctl-helper.o file.o hostname.o getlogin.o getopt.o getpass.o group.o \
	hostid.o pause.o pwd.o sys.o user.o)
