#
# Makefile for libphoenix (fcntl)
#
# Copyright 2018 Phoenix Systems
# Author: Pawel Pisarczyk
#

ARCH_SRCS = file.c dir.c group.c user.c getopt.c pwd.c sys.c sysconf.c alarm.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
