#
# Makefile for libphoenix/unistd
#
# Copyright 2020 Phoenix Systems
#

OBJS += $(addprefix $(PREFIX_O)unistd/, alarm.o crypt.o dir.o file.o gethostname.o getlogin.o getopt.o getpass.o group.o pwd.o sys.o sysconf.o user.o)
