#
# Makefile for libphoenix (arch/ia32)
#
# Copyright 2017 Phoenix Systems
# Author: Pawel Pisarczyk
#

ARCH_ASMS := syscalls.S _start.S jmp.S
ARCH_SRCS := string.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
