#
# Makefile for libphoenix/arch/ia32
#
# Copyright 2017, 2020 Phoenix Systems
# Author: Pawel Pisarczyk
#

OBJS += $(addprefix $(PREFIX_O)arch/ia32/, _start.o syscalls.o jmp.o signal.o string.o reboot.o)
