#
# Makefile for libphoenix/regex
#
# Copyright 2018, 2020 Phoenix Systems
# Author: Jan Sikorski, Pawel Pisarczyk
#

OBJS += $(addprefix $(PREFIX_O)regex/, collate.o collcmp.o fnmatch.o glob.o regcomp.o regerror.o regexec.o regfree.o)

#wordexp.c wordfree.c
