#
# Makefile for libphoenix (foreign)
#
# Copyright 2018 Phoenix Systems
# Author: Jan Sikorski
#

ARCH_SRCS := collate.c collcmp.c fnmatch.c glob.c regcomp.c regerror.c regexec.c regfree.c #wordexp.c wordfree.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
