#
# Makefile for libphoenix/arch/sparcv8leon3
#
# Copyright 2022 Phoenix Systems
# Author: Lukasz Leczkowski
#

OBJS += $(addprefix $(PREFIX_O)arch/sparcv8leon3/, _start.o syscalls.o jmp.o signal.o string.o reboot.o)
