#
# Makefile for libphoenix/arch/arm/multilib
#
# Copyright 2025 Phoenix Systems
#
# %LICENSE%
#

OBJS += $(addprefix $(PREFIX_O)arch/arm/multilib/, syscalls.o reboot.o)

OBJS += $(addprefix $(PREFIX_O)arch/arm/multilib/, jmp.o signal.o string.o)
