#
# Makefile for libphoenix (termios)
#
# Copyright 2018 Phoenix Systems
# Author: Pawel Pisarczyk
#

ARCH_SRCS := termios.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
