#
# Makefile for libphoenix/arch/aarch64
#
# Copyright 2024 Phoenix Systems
# Author: Jacek Maksymowicz
#

OBJS += $(addprefix $(PREFIX_O)arch/aarch64/, syscalls.o jmp.o signal.o reboot.o memcpy.o memset.o)
CRT0_OBJS += $(addprefix $(PREFIX_O)arch/aarch64/, crt0.o)
