#
# Makefile for Phoenix-RTOS kernel (test)
#
# Copyright 2012-2015 Phoenix Systems
# Copyright 2001, 2005-2006 Pawel Pisarczyk
#

ARCH_SRCS := locale.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
