#
# Makefile for libphoenix (net)
#
# Copyright 2017 Phoenix Systems
# Author: Marek Białowąs
#

ARCH_SRCS = $(wildcard *.c)

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
