# vim:sw=2:ts=2
name: ci

# on events
on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'

jobs:
  call-ci:
    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/ci-submodule.yml@master
    with:
      nightly: true
    secrets: inherit
