#
# Makefile for libphoenix/net
#
# Copyright 2017, 2020 Phoenix Systems
# Author: Marek Białowąs, Pawel Pisarczyk
#

OBJS += $(addprefix $(PREFIX_O)net/, if_nametoindex.o inet.o inet_addr.o inet_aton.o inet_ntoa.o inet_ntop.o inet_pton.o)
