#
# Makefile for libphoenix/arch/riscv64
#
# Copyright 2017, 2018, 2020 Phoenix Systems
# Author: Pawel Pisarczyk
#

OBJS += $(addprefix $(PREFIX_O)arch/riscv64/, _start.o syscalls.o string.o signal.o reboot.o)

