#
# Makefile for libphoenix (arch/riscv64)
#
# Copyright 2017, 2018 Phoenix Systems
# Author: Pawel Pisarczyk
#

ARCH_ASMS := _start.S syscalls.S string.S signal.S
ARCH_SRCS := reboot.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
