#
# Makefile for libphoenix (arch/arm-imx)
#
# Copyright 2017 Phoenix Systems
# Author: Pawel Pisarczyk
#

ARCH_ASMS := _start.S syscalls.S
ARCH_SRCS := string.c jmp.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
