#
# Makefile for libphoenix/arch/arm-imx
#
# Copyright 2017, 2020 Phoenix Systems
# Author: Pawel Pisarczyk
#

OBJS += $(addprefix $(PREFIX_O)arch/arm-imx/, _start.o syscalls.o jmp.o signal.o string.o reboot.o)
